export const siteConfig = {
  name: "Grani Bel",
  businessName: "Grani Bel - Revestimentos em Pedras Naturais e Marmoraria",
  description: "Revestimentos em pedras naturais e marmoraria para valorizar sua obra. Catálogo completo de mármores, granitos, quartzito, quartzo e lâminas ultracompactas. Atendimento rápido via WhatsApp.",
  url: "https://granibel.com",
  ogImage: "/images/og-granibel.jpg",
  whatsapp: {
    number: "5555992204461",
    link: "https://wa.me/5555992204461",
  },
  links: {
    whatsapp: "https://wa.me/5555992204461",
    instagram: "https://www.instagram.com/marmoraria_grani_bel/",
  },
  // SEO Keywords
  keywords: [
    "pedras naturais",
    "marmoraria",
    "revestimento em pedra",
    "mármores",
    "granitos",
    "quartzito",
    "quartzo",
    "lâminas ultracompactas",
    "fachada em pedra",
    "área gourmet",
    "lajinha",
    "pedra moledos",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
    "pedras para soleira",
    "pedras para peitoril",
    "pedras para bancada",
    "pedras para balcão",
    "pedras para mesa",
    "pedras para pia",
    "pedras para lavabo",
    "pedras para cozinha",
    "pedras para banheiro",
    "pedras para sala",
    "pedras para quarto",
    "pedras para varanda",
    "pedras para sacada",
    "pedras para terraço",
    "pedras para quintal",
    "pedras para jardim",
    "pedras para piscina",
    "pedras para escada",
    "pedras para lareira",
    "pedras para churrasqueira",
  ],
}

export type SiteConfig = typeof siteConfig
